### ISSUE TITLE
ImportError: No module named Tkinter

### ISSUE THREAD

**Issue by xzt41** [xzt41/RiboCode#3]
The Tkinter is needed when import the matplotlib. If the following error is returned, pls check whether the tkinter package is installed.  On Linux platform, users can install this package using follow command:
`yum install tkinter`
or 
`apt-get install tkinter` 

> Traceback (most recent call last):
  File "/usr/bin/metaplots", line 7, in <module>
    from RiboCode.metaplots import main
  File "/usr/lib64/python2.7/site-packages/RiboCode/metaplots.py", line 7, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib64/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib64/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/usr/lib/python2.7/site-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/lib/python2.7/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/lib/python2.7/site-packages/six.py", line 82, in _import_module
    __import__(name)
ImportError: No module named Tkinter

**Comment by appi147** [comment]
Hi @xzt41 
For python2:
`apt-get install python-tk`
For python3:
`apt-get install python3-tk`

**Comment by xzt41** [comment]
Thanks @appi147
